name: CI

on:
    push:
    pull_request:

jobs:
    ci:
        name: "Mocha test"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v1
              with:
                  node-version: 18

            - uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: |
                      - recursive: true
                      args: [--frozen-lockfile, --strict-peer-dependencies]

            - run: pnpm run test
